# AeroSpace configuration
# See: https://nikitabobko.github.io/AeroSpace/guide

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Define the main mode
[mode.main.binding]
# Focus windows with hjkl (vim-style)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows with shift+hjkl
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Focus monitors with ctrl+hl
alt-ctrl-h = 'focus-monitor left'
alt-ctrl-l = 'focus-monitor right'

# Move windows to monitors with ctrl+shift+hl
alt-ctrl-shift-h = 'move-node-to-monitor left'
alt-ctrl-shift-l = 'move-node-to-monitor right'

# Switch workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move windows to workspaces
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Toggle between horizontal and vertical splits
alt-slash = 'layout tiles horizontal vertical'

# Toggle fullscreen
alt-f = 'fullscreen'

# Enter resize mode
alt-r = 'mode resize'

# Reload config
alt-shift-r = 'reload-config'

# Resize mode
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 2
8 = 2
9 = 2
