" TODO: copy paste from tmux


let mapleader = "-"
let maplocalleader = "="

 " Neovim {{{
set dir=~/.vim/.cache
set undofile
set spellfile=~/.vim/spell/en.utf-8.add
if has('nvim')
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath=&runtimepath
    set undodir=~/.vim/undodir_nvim
    " Nvim has a rendering problem with title
    set notitle
else
    set undodir=~/.vim/undodir
 endif
 " }}}

" Plugin Configuration {{{
" ctrlp {{{
set wildignore+=*/node_modules/*,*pycache*
" }}}

" vim-iced {{{
let g:iced_enable_default_key_mappings = v:true
let g:sexp_enable_insert_mode_mappings = 0
" }}}

" NerdTree {{{
command! Tree :NERDTree
nnoremap <F6> :NERDTreeToggle<CR>
nnoremap <F5> :UndotreeToggle<CR>
"}}}

" Goyo {{{
function! s:goyo_enter() abort
    colorscheme darkblue
    set nocursorline
    set nocursorcolumn
    set spell
endfunction

function! s:goyo_leave() abort
    colorscheme murphy
    set cursorline
    set cursorcolumn
    set nospell
    q
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
" }}}

" Ultisnips {{{
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-f>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"
" }}}

" Rainbow parentheses {{{
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0
au VimEnter * RainbowParenthesesToggle
au VimEnter * RainbowParenthesesLoadRound
au VimEnter * RainbowParenthesesLoadSquare
au VimEnter * RainbowParenthesesLoadBraces
" }}}
" }}}

" Aesthetics {{{
syntax on
colorscheme murphy

set number rnu
set cursorline cursorcolumn
set scrolloff=5

" Tmux color fix
set background=dark
set t_Co=256
" Needed to backspace over eol on mac
set backspace=2
set noerrorbells

set smartcase ignorecase noincsearch
set path+=**3
set wildmenu

set autoread

set nosplitbelow splitright

set softtabstop=4
set autoindent expandtab
set shiftwidth=4

filetype plugin indent on

let g:markdown_fenced_languages = ['html', 'js=javascript', 'python', 'clojure', 'javascript']
"}}}

" Normal Mode Commands {{{
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <S-TAB> gT
nnoremap <TAB> gt
nnoremap <C-u> <C-I>
nnoremap <C-v> "+p
inoremap <C-v> <Esc>"+pa
"}}}

" Skeletons {{{
augroup skeletons
	autocmd!
	autocmd BufNewFile *.sh 0r ~/.vim/skeletons/bash.sh
augroup END
"}}}

" Extending Files {{{
nnoremap <leader>ev :split $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>es :UltiSnipsEdit<cr>

nnoremap <leader>n :split ~/notes/notes.wofl<CR>:Goyo<CR>
nnoremap <leader>j :split ~/notes/journal.txt<CR>:Goyo<CR>
nnoremap <leader>q :vsp ~/gpt_qs.txt<CR>Go>><ESC>
" }}}

" Insert Mode Commands {{{
inoremap <c-u> <esc>lviwUwi
inoremap jk <esc>
vnoremap jk <esc>
cnoremap jk <C-f>
inoremap :w <esc>:w<cr>
"}}}

" Livewriting mode {{{
function! ToggleWritingMode() abort
	if !exists('#WriteMode#InsertLeave')
		augroup WriteMode
			autocmd!
			autocmd InsertLeave * w
		augroup END
	else
		augroup WriteMode
			autocmd!
		augroup END
	endif
endfunction
command! WriteLive call ToggleWritingMode()
" }}}

" Abbreviations {{{

" I'm always making these types
command! Wq :wq
command! WQ :wq
command! Q :q
command! W :w
command! Wqa :wqa

" TODO: handle suffixes? Have toggle to handle which to generate? -v for verb?
function! Abbrevword(...) abort
	let toabbr = a:1
	let target = join(a:000[1:]," ") 
	execute ("iabbrev " . toabbr ." ".target)
	execute ("iabbrev " . toabbr."s ".target."s")
	execute ("iabbrev " . (toupper(toabbr[0]).toabbr[1:])." ".toupper(target[0]) . target[1:])
	execute ("iabbrev " . (toupper(toabbr[0]).toabbr[1:]."s ".toupper(target[0]).target[1:]."s"))
endfunction
command! -nargs=+ AbbrevWord call Abbrevword(<f-args>)

" Probability
AbbrevWord distr distribution
AbbrevWord disted distributed
AbbrevWord rv random variable
AbbrevWord rV random Variable
AbbrevWord prob probability
AbbrevWord probly probably
AbbrevWord prbs probabilities
AbbrevWord whp with high probability
AbbrevWord rMT random matrix theory

" Logic (Mathematical bent but not purely)
AbbrevWord ew elsewhere
AbbrevWord tf therefore
AbbrevWord wlog without loss of generality
AbbrevWord wrt with respect to
AbbrevWord te there exists
AbbrevWord fa for all
AbbrevWord lhs left hand side
AbbrevWord rhs right hand side
AbbrevWord defin definition
AbbrevWord defly definitely
AbbrevWord b4 before
AbbrevWord im I'm
AbbrevWord ive I've
AbbrevWord ill I'll
AbbrevWord fn function
AbbrevWord st such that
AbbrevWord iff if and only if
AbbrevWord sa such as
AbbrevWord ow otherwise
AbbrevWord resp respectively
AbbrevWord bc because
AbbrevWord otoh on the other hand
AbbrevWord rprv representative
AbbrevWord wo without
AbbrevWord wha whatever
AbbrevWord surj surjective
AbbrevWord inj injective
AbbrevWord bij bijective
AbbrevWord iso isomorphism

" Linear Algebra
AbbrevWord ind independent
AbbrevWord indy independently
AbbrevWord indc independence
AbbrevWord linind linearly independent
AbbrevWord codim codimension
AbbrevWord cok cokernel
AbbrevWord dmn dimension
AbbrevWord dmnl dimensional
AbbrevWord vs vector space
AbbrevWord rel relationship

" General Math
AbbrevWord expy exponentially
AbbrevWord clh Cohen-Lenstra heuristic
AbbrevWord cl Cohen-Lenstra
AbbrevWord sst semi-standard Young tableaux
AbbrevWord inj injective
AbbrevWord padic $p$-adic
AbbrevWord poly polynomial
AbbrevWord seq sequence
AbbrevWord ctns continuous
iabbrev i I
AbbrevWord y why
AbbrevWord b be
AbbrevWord dont don't
AbbrevWord cant can't
AbbrevWord id I'd
AbbrevWord ab about
AbbrevWord mb maybe
AbbrevWord bt but
AbbrevWord wev whatever

" Analysis
AbbrevWord triineq triangle inequality
AbbrevWord tbt therefore by the
AbbrevWord ineq inequality

iabbrev ret return
AbbrevWord jmail jakethekoenig@gmail.com

" MTG
AbbrevWord gy graveyard
AbbrevWord bf battlefield

" }}}
