name: CI

on:
  push:
  pull_request:

jobs:
  nvim-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Run headless tests
        run: |
          nvim --version
          nvim --headless -Nu test/minvimrc -S test/test_terminal_yank.vim
